/**
 * Generated by scripts/gen-db-types.mjs — do not edit by hand.
 * Regenerate after any migration with `pnpm db:types`.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Enums = {
  attendance_status: "present" | "late" | "absent" | "pending_review" | "rejected";
  punch_method: "geofence" | "supervisor_override" | "auto_close";
  shift_status: "scheduled" | "in_progress" | "completed" | "missed" | "cancelled";
  user_role: "admin" | "supervisor" | "guard" | "client";
};

export type Database = {
  public: {
    Tables: {
      attendance: {
        Row: {
          id: string;
          shift_id: string | null;
          guard_id: string;
          site_id: string;
          check_in_at: string | null;
          check_in_lat: number | null;
          check_in_lng: number | null;
          check_in_accuracy_m: number | null;
          check_in_distance_m: number | null;
          check_in_photo_key: string | null;
          check_in_method: Enums["punch_method"];
          check_out_at: string | null;
          check_out_lat: number | null;
          check_out_lng: number | null;
          check_out_accuracy_m: number | null;
          check_out_distance_m: number | null;
          check_out_photo_key: string | null;
          check_out_method: Enums["punch_method"] | null;
          worked_minutes: number | null;
          overtime_minutes: number | null;
          status: Enums["attendance_status"];
          device_reported_at: string | null;
          ip: string | null;
          user_agent: string | null;
          reviewed_by: string | null;
          review_note: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shift_id?: string | null;
          guard_id: string;
          site_id: string;
          check_in_at?: string | null;
          check_in_lat?: number | null;
          check_in_lng?: number | null;
          check_in_accuracy_m?: number | null;
          check_in_distance_m?: number | null;
          check_in_photo_key?: string | null;
          check_in_method?: Enums["punch_method"];
          check_out_at?: string | null;
          check_out_lat?: number | null;
          check_out_lng?: number | null;
          check_out_accuracy_m?: number | null;
          check_out_distance_m?: number | null;
          check_out_photo_key?: string | null;
          check_out_method?: Enums["punch_method"] | null;
          worked_minutes?: number | null;
          overtime_minutes?: number | null;
          status?: Enums["attendance_status"];
          device_reported_at?: string | null;
          ip?: string | null;
          user_agent?: string | null;
          reviewed_by?: string | null;
          review_note?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shift_id?: string | null;
          guard_id?: string;
          site_id?: string;
          check_in_at?: string | null;
          check_in_lat?: number | null;
          check_in_lng?: number | null;
          check_in_accuracy_m?: number | null;
          check_in_distance_m?: number | null;
          check_in_photo_key?: string | null;
          check_in_method?: Enums["punch_method"];
          check_out_at?: string | null;
          check_out_lat?: number | null;
          check_out_lng?: number | null;
          check_out_accuracy_m?: number | null;
          check_out_distance_m?: number | null;
          check_out_photo_key?: string | null;
          check_out_method?: Enums["punch_method"] | null;
          worked_minutes?: number | null;
          overtime_minutes?: number | null;
          status?: Enums["attendance_status"];
          device_reported_at?: string | null;
          ip?: string | null;
          user_agent?: string | null;
          reviewed_by?: string | null;
          review_note?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: number;
          actor_id: string | null;
          actor_code: string | null;
          action: string;
          entity: string | null;
          entity_id: string | null;
          detail: Json | null;
          ip: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          actor_code?: string | null;
          action: string;
          entity?: string | null;
          entity_id?: string | null;
          detail?: Json | null;
          ip?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          actor_code?: string | null;
          action?: string;
          entity?: string | null;
          entity_id?: string | null;
          detail?: Json | null;
          ip?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          employee_code: string;
          role: Enums["user_role"];
          full_name: string;
          phone: string | null;
          photo_key: string | null;
          active: boolean;
          joined_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          employee_code: string;
          role?: Enums["user_role"];
          full_name: string;
          phone?: string | null;
          photo_key?: string | null;
          active?: boolean;
          joined_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_code?: string;
          role?: Enums["user_role"];
          full_name?: string;
          phone?: string | null;
          photo_key?: string | null;
          active?: boolean;
          joined_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      shifts: {
        Row: {
          id: string;
          site_id: string;
          guard_id: string;
          starts_at: string;
          ends_at: string;
          status: Enums["shift_status"];
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          guard_id: string;
          starts_at: string;
          ends_at: string;
          status?: Enums["shift_status"];
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          guard_id?: string;
          starts_at?: string;
          ends_at?: string;
          status?: Enums["shift_status"];
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sites: {
        Row: {
          id: string;
          name: string;
          client_name: string | null;
          address: string | null;
          district: string | null;
          lat: number;
          lng: number;
          geofence_radius_m: number;
          polygon: Json | null;
          shift_start: string | null;
          shift_end: string | null;
          grace_minutes: number;
          standard_shift_minutes: number;
          max_accuracy_m: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          client_name?: string | null;
          address?: string | null;
          district?: string | null;
          lat: number;
          lng: number;
          geofence_radius_m?: number;
          polygon?: Json | null;
          shift_start?: string | null;
          shift_end?: string | null;
          grace_minutes?: number;
          standard_shift_minutes?: number;
          max_accuracy_m?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          client_name?: string | null;
          address?: string | null;
          district?: string | null;
          lat?: number;
          lng?: number;
          geofence_radius_m?: number;
          polygon?: Json | null;
          shift_start?: string | null;
          shift_end?: string | null;
          grace_minutes?: number;
          standard_shift_minutes?: number;
          max_accuracy_m?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      submissions: {
        Row: {
          id: string;
          kind: string;
          status: string;
          created_at: string;
          name: string;
          email: string | null;
          phone: string;
          company: string | null;
          subject: string | null;
          message: string | null;
          service: string | null;
          site_type: string | null;
          district: string | null;
          headcount: string | null;
          start_when: string | null;
          vacancy_id: string | null;
          vacancy_title: string | null;
          age: string | null;
          education: string | null;
          experience: string | null;
          user_agent: string | null;
          remote_ip: string | null;
        };
        Insert: {
          id: string;
          kind: string;
          status?: string;
          created_at?: string;
          name: string;
          email?: string | null;
          phone: string;
          company?: string | null;
          subject?: string | null;
          message?: string | null;
          service?: string | null;
          site_type?: string | null;
          district?: string | null;
          headcount?: string | null;
          start_when?: string | null;
          vacancy_id?: string | null;
          vacancy_title?: string | null;
          age?: string | null;
          education?: string | null;
          experience?: string | null;
          user_agent?: string | null;
          remote_ip?: string | null;
        };
        Update: {
          id?: string;
          kind?: string;
          status?: string;
          created_at?: string;
          name?: string;
          email?: string | null;
          phone?: string;
          company?: string | null;
          subject?: string | null;
          message?: string | null;
          service?: string | null;
          site_type?: string | null;
          district?: string | null;
          headcount?: string | null;
          start_when?: string | null;
          vacancy_id?: string | null;
          vacancy_title?: string | null;
          age?: string | null;
          education?: string | null;
          experience?: string | null;
          user_agent?: string | null;
          remote_ip?: string | null;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      geo_distance_m: {
        Args: {
          lat1: number;
          lng1: number;
          lat2: number;
          lng2: number;
        };
        Returns: number;
      };
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_staff: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      my_role: {
        Args: Record<PropertyKey, never>;
        Returns: Enums["user_role"];
      };
      point_in_ring: {
        Args: {
          ring: Json;
          p_lat: number;
          p_lng: number;
        };
        Returns: boolean;
      };
      site_fence_check: {
        Args: {
          p_site_id: string;
          p_lat: number;
          p_lng: number;
        };
        Returns: { inside: boolean; distance_m: number }[];
      };
    };
    Enums: Enums;
    CompositeTypes: { [_ in never]: never };
  };
};

/** Shorthand: `Row<"sites">` instead of the full path. */
export type Row<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
