/**
 * The realtime contract.
 *
 * Channel and event names, in one place, because a subscriber that listens on
 * `site-sos` while the publisher broadcasts to `site:sos` fails silently — the
 * socket connects, the subscription succeeds, and nothing ever arrives. That is
 * a bad failure for a panic button to have, so the strings are generated by
 * functions both sides import rather than typed twice.
 *
 * Two mechanisms, for two different jobs:
 *
 *   BROADCAST is used for positions. Postgres Changes bills one message per row
 *   per subscriber, so streaming 200 guards' pings to three admins costs three
 *   messages per ping — millions a month. Instead a single job publishes one
 *   message carrying every position, on a timer, and cost scales with the number
 *   of people watching rather than the number of guards moving.
 *
 *   POSTGRES CHANGES is used for SOS and roster edits, where the events are rare,
 *   individually important, and must not be batched behind a timer.
 */

/** Positions for every on-duty guard, batched. Admins and supervisors only. */
export const LIVE_MAP_CHANNEL = "live-map";

/** Positions for one site: what a client watching their own gate subscribes to. */
export function siteChannel(siteId: string): string {
  return `site:${siteId}`;
}

/** A guard's own device channel — used to push a tracking-mode change down. */
export function guardChannel(guardId: string): string {
  return `guard:${guardId}`;
}

export const EVENTS = {
  /** A batch of positions. Payload: `PositionBatch`. */
  positions: "positions",
  /** An SOS was raised, acknowledged or closed. Payload: `SosEvent`. */
  sos: "sos",
  /** Switch tracking cadence. Payload: `{ mode: TrackingMode, until?: string }`. */
  tracking: "tracking",
} as const;

/**
 * How often the batch goes out.
 *
 * Fifteen seconds is below the threshold at which a dot on a map stops feeling
 * live, and it fixes the message bill at roughly 173,000 per viewer per month
 * however many guards are on duty.
 */
export const BATCH_INTERVAL_MS = 15_000;

/**
 * One guard's position inside a batch.
 *
 * This must stay identical to the object `broadcast_positions()` builds in
 * 0005_live_location.sql. There is no type checking across that boundary — a field
 * renamed in the SQL and not here reads as `undefined` at run time, on a map, during
 * a shift. When you change one, change both.
 */
export type LivePosition = {
  guard_id: string;
  site_id: string | null;
  lat: number;
  lng: number;
  accuracy_m: number;
  heading: number | null;
  speed_mps: number | null;
  /** Percentage, 0–100. Tells "stopped moving" apart from "the phone died". */
  battery: number | null;
  /** The fence verdict at the moment of the ping, computed in Postgres. */
  inside_fence: boolean | null;
  /** Metres from the site centre, rounded to one decimal place by the broadcaster. */
  distance_m: number | null;
  mode: "on_duty" | "emergency";
  /** Server time the position was recorded. ISO 8601. */
  recorded_at: string;
};

export type PositionBatch = {
  /** Server time the batch was assembled, so a client can age every dot in it. */
  at: string;
  positions: LivePosition[];
};

export type SosEvent = {
  id: string;
  site_id: string;
  raised_by: string;
  status: string;
  lat: number | null;
  lng: number | null;
  raised_at: string;
};
